name: omniverse
description: A new Flutter package.
version: 0.0.1
author: Phaylali
homepage: https://omniverse.dev

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # General Packages
  get:
  get_storage:
  flutter_icons:

  # Firebase Packages
  firebase_auth:
  cloud_firestore:
  firebase_core: 
  firebase_analytics:
  thumbnailer:
  url_launcher:
  native_pdf_view:

  # App Specific Packages
  flutter_sheet_localization:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator:
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png